// COPYRIGHT Dassault Systemes 2022
//===================================================================
//
// TRACommandAddin.h
// Provide implementation to interface
//    CATIShapeDesignWorkshopAddin

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	TRAECommandAddin
//EXTENSIONTYPE:	DataExtension

//    TIE: CATIShapeDesignWorkshopAddin

//End CAA2 Wizard Generation Report
//
//  Jun 2022  Creation: Code generated by the CAA wizard  Dell
//===================================================================
#ifndef TRACommandAddin_H
#define TRACommandAddin_H

#include "CATBaseUnknown.h"

class CATCmdContainer;

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATIShapeDesignWorkshopAddin
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class TRACommandAddin: public CATBaseUnknown

{
  CATDeclareClass;

  public:

	 void CreateCommands();

     
     CATCmdContainer * CreateToolbars();

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     TRACommandAddin ();
     virtual ~TRACommandAddin ();


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  TRACommandAddin (TRACommandAddin &);
  TRACommandAddin& operator=(TRACommandAddin&);

};

//-----------------------------------------------------------------------

#endif
