D:\CAA\TRANagaTest4WS\.\TRACommandAddinFW\various\win_b64\HList\PrivateInterfaces.hl
D:\CAA\TRANagaTest4WS\.\TRACommandAddinFW\various\win_b64\HList\ProtectedInterfaces.hl
D:\CAA\TRANagaTest4WS\.\TRACommandAddinFW\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ApplicationFrame\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ApplicationFrame\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\AutomationInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\AutomationInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\BatchInfrastructure\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\BatchInfrastructure\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATDataCompatibilityInfra\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATDataCompatibilityInfra\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATIADataBasics\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATIADataBasics\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATJavaBridge\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATJavaBridge\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATPDMBaseInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATPDMBaseInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATPLMDictionary\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATPLMDictionary\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATTechnologicalPackageUIItf\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATTechnologicalPackageUIItf\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATVirtualVaultSystem\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\CATVirtualVaultSystem\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Communications\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Communications\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Dialog\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Dialog\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\DialogEngine\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\DialogEngine\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\GSMInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\GSMInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Graph\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Graph\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\InfInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\InfInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\InteractiveInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\InteractiveInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\KnowledgeInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\KnowledgeInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Mainwin\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Mainwin\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Mathematics\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Mathematics\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\MecModInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\MecModInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerBase\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerBase\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerCATIA\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerCATIA\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerCollection\various\win_b64\HList\PrivateInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerCollection\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerCollection\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerNavigator\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerNavigator\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerSystem\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectModelerSystem\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectSpecsModeler\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ObjectSpecsModeler\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ProductStructureInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\ProductStructureInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\SketcherInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\SketcherInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\SpecialAPI\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\SpecialAPI\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\System\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\System\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\VBA\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\VBA\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Visualization\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\Visualization\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\VisualizationBase\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\VisualizationBase\various\win_b64\HList\PublicInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\XMLParser\various\win_b64\HList\ProtectedInterfaces.hl
C:\Program Files\Dassault Systemes\B19\.\XMLParser\various\win_b64\HList\PublicInterfaces.hl
