// COPYRIGHT Dassault Systemes 2022
//===================================================================
//
// TRACommandDlg.cpp
// The dialog : TRACommandDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Jun 2022  Creation: Code generated by the CAA wizard  Dell
//===================================================================
#include "TRACommandDlg.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#ifdef TRACommandDlg_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#include "CATDlgContextualMenu.h"

#endif




//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
TRACommandDlg::TRACommandDlg() :
  CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
//CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"TRACommandDlg",CATDlgWndBtnOKCancel|CATDlgGridLayout
//END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
                               )
{
//CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
 _Frame1 = NULL;
 _Point1 = NULL;
 _Point2 = NULL;
 _Point3 = NULL;
 _pointSelectorList001 = NULL;
 _pointSelectorList002 = NULL;
 _pointSelectorList003 = NULL;
 _pCtxMenuClear = NULL;
//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
}

//------- ------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
TRACommandDlg::~TRACommandDlg()
{
//  Do not delete the control elements of your dialog: 
//     this is done automatically
//  --------------------------------------------------
//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 _Frame1 = NULL;
 _Point1 = NULL;
 _Point2 = NULL;
 _Point3 = NULL;
 _pointSelectorList001 = NULL;
 _pointSelectorList002 = NULL;
 _pointSelectorList003 = NULL;
 _pCtxMenuClear = NULL;
//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
}



void TRACommandDlg::Build()
{
//  TODO: This call builds your dialog from the layout declaration file
//  -------------------------------------------------------------------

//CAA2 WIZARD WIDGET CONSTRUCTION SECTION
 _Frame1 = new CATDlgFrame(this, "Frame1", CATDlgFraNoFrame|CATDlgGridLayout);
_Frame1 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Point1 = new CATDlgLabel(_Frame1, "Point1");
_Point1 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Point2 = new CATDlgLabel(this, "Point2");
_Point2 -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _Point3 = new CATDlgLabel(this, "Point3");
_Point3 -> SetGridConstraints(2, 0, 1, 1, CATGRID_4SIDES);

//CATUnicodeString  iString = "No Selection";
 _pointSelectorList001 = new CATDlgSelectorList(this, "pointSelectorList001");
 _pointSelectorList001 -> SetVisibleTextHeight(1);
 _pointSelectorList001 -> SetVisibleTextWidth(10);
 _pointSelectorList001->SetLine("Select Point1");
_pointSelectorList001 -> SetGridConstraints(0, 2, 1, 1, CATGRID_4SIDES);
 _pointSelectorList002 = new CATDlgSelectorList(this, "pointSelectorList002");
 _pointSelectorList002 -> SetVisibleTextHeight(1);
 _pointSelectorList002 -> SetVisibleTextWidth(10);
  _pointSelectorList002->SetLine("Select Point2");
_pointSelectorList002 -> SetGridConstraints(1, 2, 1, 1, CATGRID_4SIDES);
 _pointSelectorList003 = new CATDlgSelectorList(this, "SelectorList008");
 _pointSelectorList003 -> SetVisibleTextHeight(1);
 _pointSelectorList003 -> SetVisibleTextWidth(10);
 _pointSelectorList003->SetLine("Select Point3");
_pointSelectorList003 -> SetGridConstraints(2, 2, 1, 1, CATGRID_4SIDES);

_pCtxMenuClear = new CATDlgContextualMenu(_pointSelectorList001, CATString("CtxMenuClear"), CATDlgCtxEmpty);
_pCtxMenuClear = new CATDlgContextualMenu(_pointSelectorList002, CATString("CtxMenuClear"), CATDlgCtxEmpty);
_pCtxMenuClear = new CATDlgContextualMenu(_pointSelectorList003, CATString("CtxMenuClear"), CATDlgCtxEmpty);
//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION

//CAA2 WIZARD CALLBACK DECLARATION SECTION
//END CAA2 WIZARD CALLBACK DECLARATION SECTION

}


void TRACommandDlg::SetPoint1SelectorList(const CATUnicodeString & Name)
  { 
      _pointSelectorList001->ClearLine();  
      _pointSelectorList001->SetLine(Name);
      ClearSelectForPoint1SelectorList();
      //SetSelectForPoint2SelectorList();
  }

  void TRACommandDlg::SetPoint2SelectorList(const CATUnicodeString & Name)
  { 
    
      _pointSelectorList002->ClearLine();
      _pointSelectorList002->SetLine(Name);
     // SetSelectForPoint3SelectorList();
  
  }

   void TRACommandDlg::SetPoint3SelectorList(const CATUnicodeString & Name)
  { 
    
      _pointSelectorList003->ClearLine();
      _pointSelectorList003->SetLine(Name);
   //   SetSelectForPoint1SelectorList();
  
  }

void TRACommandDlg::SetSelectForPoint1SelectorList()
{
    int TableRow = 0;
    _pointSelectorList001->SetSelect( &TableRow, 1, 0);
}

void TRACommandDlg::SetSelectForPoint2SelectorList()
{
    int TableRow = 0;
    _pointSelectorList002->SetSelect( &TableRow, 1, 0);
}

void TRACommandDlg::SetSelectForPoint3SelectorList()
{
    int TableRow = 0;
    _pointSelectorList003->SetSelect( &TableRow, 1, 0);
}


void TRACommandDlg::ClearSelectForPoint1SelectorList()
{
    _pointSelectorList001->ClearSelect();
}

void TRACommandDlg::ClearSelectForPoint2SelectorList()
{
    _pointSelectorList002->ClearSelect();
}

void TRACommandDlg::ClearSelectForPoint3SelectorList()
{
    _pointSelectorList003->ClearSelect();
}

void TRACommandDlg::ClearSelectForPoint3SelectorListContextual()
{

	
    
	_pointSelectorList003->ClearLine();
	_pointSelectorList003->SetLine("Select Point3");
	SetSelectForPoint3SelectorList();
}

CATDlgSelectorList * TRACommandDlg::GetPoint1SelectorList()
{
    return _pointSelectorList001;
}

CATDlgSelectorList * TRACommandDlg::GetPoint2SelectorList()
{
    return _pointSelectorList002;
}

CATDlgSelectorList * TRACommandDlg::GetPoint3SelectorList()
{
    return _pointSelectorList003;
}

void TRACommandDlg::ClearSelect(CATUnicodeString iSelectorListName)
{
	if(iSelectorListName == "SelectorList1")
	{
		_pointSelectorList002->ClearSelect();
		_pointSelectorList003->ClearSelect();
	}
	else if (iSelectorListName == "SelectorList2")
	{
		_pointSelectorList001->ClearSelect();
		_pointSelectorList003->ClearSelect();
	}
	else
	{
		_pointSelectorList001->ClearSelect();
		_pointSelectorList002->ClearSelect();
	}

	
}

//CATDlgContextualMenu* GetCtxMenuClear()
//{ 
//	return _pCtxMenuClear ; 
//}