// COPYRIGHT Dassault Systemes 2022
//===================================================================
//
// TRACommandDlg.h
// The dialog : TRACommandDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   DIALOG
//End CAA2 Wizard Generation Report
//
//  Jun 2022  Creation: Code generated by the CAA wizard  Dell
//===================================================================
#ifndef TRACommandDlg_H
#define TRACommandDlg_H

#include "TRACommandAddinMod.h"
#include "CATDlgDialog.h"
#include "CATDlgInclude.h"
#include "CATDlgContextualMenu.h"


//----------------------------------------------------------------------

/**
 * Describe the purpose of your panel here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog framework.
 * (consult base class description).
 */
class ExportedByTRACommandAddinMod TRACommandDlg: public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( TRACommandDlg, CATDlgDialog )

  public:

  TRACommandDlg();
  virtual ~TRACommandDlg();

  void Build ();

  void SetPoint1SelectorList(const CATUnicodeString & Name);
  void SetPoint2SelectorList(const CATUnicodeString & Name);
  void SetPoint3SelectorList(const CATUnicodeString & Name);

  void SetSelectForPoint1SelectorList();
  void SetSelectForPoint2SelectorList();
  void SetSelectForPoint3SelectorList();

  void ClearSelectForPoint1SelectorList();
  void ClearSelectForPoint2SelectorList();
  void ClearSelectForPoint3SelectorList();

  void ClearSelectForPoint3SelectorListContextual();

  CATDlgSelectorList * GetPoint1SelectorList();
  CATDlgSelectorList * GetPoint2SelectorList();
  CATDlgSelectorList * GetPoint3SelectorList();

  CATDlgContextualMenu* GetCtxMenuClear(){ return _pCtxMenuClear; }

  void ClearSelect(CATUnicodeString iSelectorListName);

   


  protected:

  private:


//CAA2 WIZARD WIDGET DECLARATION SECTION
 CATDlgFrame*      _Frame1;
 CATDlgLabel*      _Point1;
 CATDlgLabel*      _Point2;
 CATDlgLabel*      _Point3;
 CATDlgSelectorList*      _pointSelectorList001;
 CATDlgSelectorList*      _pointSelectorList002;
 CATDlgSelectorList*      _pointSelectorList003;

 CATDlgContextualMenu * _pCtxMenuClear;
//END CAA2 WIZARD WIDGET DECLARATION SECTION


 

};

//----------------------------------------------------------------------

#endif
